
<div class='letter'>
	<div class='letter_head'>

		<div class='salutation'>
			<span class='lh_el'>Lark Hill</span>
			<span class='lh_el'>2nd April 1917</span>
		</div>
		<p>My dear sweetheart wife</p>
	</div><!-- end class='letter_header'-->
<!-- --------------------------------------------------------------------------->
<p>It is now nearly one month kiddie since I received any letters from you, but heard today that there was an Australian mail in, so I am anxiously waiting for the delivery which will be in a day or so then I expect to secure a large budget from my dear wife. </p>
<p>Three of us went to the pictures and vaudeville last Friday. Very good show indeed especially the vaudeville portion would have held its own in any Sydney Theatre. As a rule the shows on the plains are very poor indeed.</p>
<p>The filling came out of one of my back teeth the other day, so visited the camp dentist on Saturday, fixed it up so everything is okay.</p>
<p>Was with Keith again on Saturday afternoon and night. He walked right over from Park House to our camp, a distance of about 9 miles. Spent a grand time together and having plenty of time at our disposal, we sat in the YMCA for several hours giving one another all the news possible. Afterwards we strolled around the camp and then had tea, we also witnessed a draft of our men leaving for France. I accompanied him a good part of the way back, on the way we met Harley Eckford and Ross Johnson. Jerry was very pleased to meet them, he also met McKay. Keith is looking grand and at the present moment no doubt he is having a good time in London, for he was to go on his 4  days disembarkation leave this morning. He also received letters from Dorothy and Annie Roberts. He is going to call on Dorothy while on leave but will see Annie some Sunday when five of them hire a car for the day. &pound;4 and drive it themselves. They are going to Bournemouth next Sunday. I have received two letters and two postcards from him but of course met him before I received the letters. He has written to you dear, since arriving on this side, so suppose you will receive it in due course. Can tell you we thoroughly enjoyed the afternoon together and if all goes well we intend to meet again on Sunday week.</p>
<p>Received another parcel from Mrs. Smith yesterday, making number seven. It contained about a dozen wheatmeal cakes and a half pound of butter. Butter is just the thing, tell you it's greatly appreciated. She is going away for a two week holiday. She said it is a wonderful thing for her to go away, considering she is 67 and has had to stay at home for years. Then this is what she wrote&rdquo; Wonder what pretty home you and Neita will be in when you are that age.&rdquo; I wonder sweetheart, have a good idea, won't it be grand and with the children running about everywhere will be just the thing. </p>
<p>Yesterday a party of us went for a walk along the River Avon to Great Durnham. Very enjoyable afternoon. Had a good tea when we arrived. Eating is the chief item here. Yesterday I did fairly well that way. This is what I had. Dinner: boiled beef and peas at the mess, on returning to  hut had a slice of bread and honey and six of Mrs. Smith cakes. Tea: two boiled eggs, eight slices of bread and butter and strawberry jam, two pieces of cake, and 2 cups of tea. On returning to camp we called at the canteen and devoured  two sausages, a slice of bread, and a cup of tea. Returned to hut and finished off two slices of bread and honey. Just going to bed when in came a couple of tins of salmon and a loaf of bread. Finished up with two slices of bread and salmon. This was an exceptional day, would that it would happen every day. Yesterday was a lovely day, but last night there was a very heavy fall of snow. Today was bright, up till about 4 o'clock then it D&hellip; will snowed again. This is English spring. Wish it would hurry up and Spring off to Summer. The sun is very seldom seen. Here are the official figures </p>
<p>December sunshine two hours</p>
<p>January sunshine 3 1/2 hours</p>
<p>February sunshine five and three-quarter hours</p>
<p>Gives one some idea what this country is like in wintertime. Of course in summer a different tale will be told, but give me dear old Maitland. Going to drop a line to Mrs. Smith  as soon as I finish this. She's going to send me a book to read Chestertons, &ldquo;Ballard of the White Horse&rdquo;. Won&rsquo;t have much time to read it but will do my best. Hope to be able to write the mater a few lines tonight also. </p>
<div class='closing'>
<p>Au revoir for the present sweetheart, sincerely hope to receive your letters tomorrow. It will be simply grand to receive some more letters, seems like months since I've had any news from my darling. Snowing heavily at present. Hope you are keeping in the best of health and everything moving along okay towards the great event. Darling I would give anything to be with you, but of course that cannot be. I will get there as soon as I possible can. My thoughts are continually on you sweetheart and wishing you every thing of the best. Will write you again in a day or so. Love kisses and embraces to my darling wife from your ever loving and devoted husband with tons and tons of kisses.</p>
<p>Don  xxxxxxxxxxxxxxxxxxxxxx and oooooooooooo</p>
<p>One of the boys just brought me in a couple of sausages and a slice of bread. Just grand. Don</p>
</div>
</div><!-- letter -->
