
<div class='letter'>
	<div class='letter_head'>

		<div class='salutation'>
			<span class='lh_el'>Camp 26</span>
			<span class='lh_el'>9th April 1917</span>
		</div>
		<p>My darling old sweetheart</p>
	</div><!-- end class='letter_header'-->
<!-- --------------------------------------------------------------------------->
<p>Your ever loving and welcomed letter received yesterday. Cannot tell you how pleased I was to receive it, I was just like a youngster with a new toy, put me in absolutely the best of spirits. </p>
<p>It is simply grand to receive your letters dear. This one I received is number 26. </p>
<p>Yesterday 4 of us went for a walk along the River Avon. After having a good feed of eggs and bread we started on our way home arriving at 8:20 PM. While away Keith called so therefore I missed him. I was extremely sorry to miss him, but it was his own fault, because I told him that I would be away for the weekend most likely. Suppose he came over on chance, tell you dear I was very sorry. Sat down straightaway and wrote him a letter making arrangements for meeting one and other next weekend. Yesterday was the first day of the summer daylight saving. The clock was advanced one hour. You say this schedule does not meet with approval in Australia, but here things are different it suits us right down to the ground. We had good light up until 9 o&rsquo;clock. Our men were very pleased with  the review last Saturday. We were congratulated by Brig. Gen. and  a number of British officers who were witnessing the march past. They said the marching etc. of the field artillery was equal if not better than the once regular British Army. The British Army referred to was the army that first went to France. The mounted portion of the artillery was said by everybody to be equal to any  artillery in the world. The men don&rsquo;t care a dam about all the flap but the officers are over pleased with the efforts of the men. Bulford people who have seen numerous parades say they have never seen a march past etc. to equal it.</p>
<p>Darling it is five months today since my leaving Australia, fancy that and I have been in England three months. The newspaper has just come in, containing good news, a general move of the British and French. From your point of view no doubt things are looking very bright and no doubt they are, Germany is getting what she deserves now. You mention taking my photos to bed with you love, well darling I've always taken that one of we two together and the bridal photo to bed with me. I&rsquo;m continually looking at them, they always put me in the best of spirits. About getting a photo of myself taken, will do so when I get into a decent town and send it straight on to my dear little wife. You must not get miserable darling, keep your pecker up. What would I give to have been with you, there would be no miserable feelings then eh darling, never mind the day is not very  far distant when I will be on my way home to my wife and our baby the greatest child ever born eh kiddie, then we will have a good time to be sure.</p>
<p>In your letter you spoke of America entering the war but the opinion held was no such luck. Strange to say I received your letter the same day as we heard that America had really declared war. Can  imagine your feelings. Although it's our opinion not to expect too much from the USA we will wait and see. Today's paper state that Cuba and Panama have also declared war, there is about only one place who has not done so yet and I expect she will shortly and that is Tonga. I mean it kiddie. As for Viv Solling I never did have any time for her but being a friend of yours said nothing. Her carryings on before she was married was enough to satisfy me but after the news you have given me well darling I do not wonder you not wanting to have anything to do with her. I certainly admire your spirit. English people on friendly terms with Germans are rotters, Viv&rsquo;s company is not good for any Australian and I'm extremely pleased to hear how you dear intend to treat a person who has friendly feelings for a German. She is absolutely a D&hellip;  rotter. Australia is too good a place for people of her class. Mrs. Smith sent me a book to read in my spare time, don't know when I will be able to read it. The Ballard of the White Horse by GK Chesterton. Supposed to be very good. I think I mentioned  in my last letter I had to received the weekly Mercury OK.</p>
<div class='closing'>
<p>There is no more to write about at present kiddie so I think I&rsquo;d better ring off. I'm extremely pleased to hear you are keeping in the best of health and everything is moving along smoothly for the great event. You have no need to worry, love, everything will be okay and after it's all over we'll see Neita McDonald a very happy and fond mother. Then wait until dad comes home, that will be the time. Well now sweetheart will now say au revoir, love, kisses and embraces to my darling wife. Tons of love.</p>
<p>From you own hubby</p>
<p>Don</p>
<p>XXXXXXXXXXXXXXXXXXXXXXX</p>
<p>Love  Don</p>
</div>
</div><!-- letter -->
