
<div class='letter'>
	<div class='letter_head'>

		<div class='salutation'>
			<span class='lh_el'>Hurdcott Camp*</span>
			<span class='lh_el'>10th November 1917</span>
		</div>
		<p>My Dearest Wife and Darling Son</p>
	</div><!-- end class='letter_header'-->
<!-- --------------------------------------------------------------------------->
<p>This will be only a short letter, kiddie, have a lot to do as I am leaving this camp tomorrow before day break. Wars warned this afternoon, this means leaving here about 5 AM for the camp at Sutton Veny. Will remain there are a few days only, then move to our artillery camp at Heytesbury. My stay there is very uncertain, anyhow France is the next move. Kiddie I wrote you last Monday stating that I received your birthday greetings cable on the 4th could not have been times better. Was overjoyed to receive it and to know that my darling was well. Have more good news for you darling, on Wednesday I received to birthday parcels one from you sweetheart and one from your mother. They too arrived well to time, don't you think so dear. You want to know exactly in what condition they arrived. Well your mothers was okay, had it for tea on Wednesday night, shared it among the boys. The socks which our darling Neville helped to push in were very welcome, in need of socks. As for the other cake it was bosker, had it for tea tonight, a little left which we are going to have for supper. Can assure you sweetheart both cakes arrived in excellent condition, simply lovely to have a feed of good cake especially when they come from my darling.
On Wednesday afternoon had one tooth stopped and one pulled, therefore making me fit to move to the next camp. At night attended a grand concert. On Thursday had a letter from Mrs Crowley, congratulating me on the arrival of our dear bonny boy. Went to another concert at night. Today received letter from mum, Phyll and Nellie. The Australian letters were the first I've received telling me that you received the particulars as to my wounds, but there are some letters are missing I'm certain. Phyll enclosed cuttings regarding the marriage of Miss Harris, some class, just like them as long as there's plenty of show they are satisfied.</p>
<p>Darling will say au revoir for the present, will write soon as I get settled in the next camp.
Love kisses and embraces to my two darlings with millions and millions of kisses and oceans of kisses from your ever own loving husband and father.</p>
<p>XXXXXXXXXXXXXXXXXXXXXX</p>
<p>Don</p>
<p>To Darling Neita and Bonny Neville</p>
<p>Australian Camps in England</p>
<p>The following camps were used by the AIF during the Great War. Some of the camps remain to&nbsp;this day and are now home to Infantry and Artillery Units of the British Army, whereas many were closed and demolished soon after the end of the war. Although practically all signs of the WW1 camps have now gone, the presence of Australians during the war is very apparent, particularly when visiting the local and military churchyards in the surrounding area, where many succumbed to their wounds or died from illness particularly the flu epidemic of 1919. Australian soldiers also left their mark on the hillsides at Codford and Fovant with &lsquo;Rising Sun&rsquo; cap badges cut into the chalk hills.
Bulford
Bulford camp was one of the original camps built on the chalky Salisbury Plain having been purchased by the army in 1897, its location ideal for training the Cavalry and Yeomanry. The original hutted camp was built in 1900 on the site of the present Sling Barracks. In 1916, an annexe to the Camp called Sling camp was occupied by New Zealand forces, then comprising four main sections: Auckland, Wellington, Otago, and Canterbury Lines. It was officially called the 4th New Zealand Infantry Brigade Reserve Camp, and trained reinforcements and casualties who were regaining fitness. A hospital was established at the army base, as a specialist venereal disease hospital. It was handed over to Australians in November 1916 and was known as&nbsp;1st Australian Dermatological Hospital.
Codford</p>
<p>With its easy rail and road access to Warminster and Salisbury Codford made an attractive location for garrisoning troops. During the First World War, there were fifteen different camps built in and around Codford, at first to accommodate British troops before their deployment to France, but in July 1916 Codford became a New Zealand Command Depot for men who, as with the AIF system, were convalescing from wounds or sickness. The Australian&nbsp;No.4 Command Depot&nbsp;moved to Codford from Wareham in Dorset in June 1917 until November of that year when it then moved to Hurdcott.
The camp is no longer there but one of the most notable features illustrating the presence of Australian soldiers is found on a nearby hill outside Codford, where a&nbsp;&lsquo;Rising Sun&rsquo;&nbsp;cap badge measuring some 175ft by 150ft high, has been cut into the chalk. Also an&nbsp;Anzac cemetery&nbsp;(photograph) is located in the village close to the church and contains the graves of thirty-one Australian and sixty-six New Zealander soldiers.
To learn about the Australians that are lying in Codford Anzac Cemetery, visit the&nbsp;WW1 Australian Soldiers &amp; Nurses who rest in the United Kingdom&nbsp;project website.
Fargo</p>
<p>Fargo was a&nbsp;Military Hospital&nbsp;that was also used for prisoners of war. It is likely that most of the 141 Australians and thirteen Americans buried in&nbsp;Durrington Cemetery&nbsp;would have been patients at Fargo. Included within the Durrington Cemetery is&nbsp;6177 Pte HC Canham&nbsp;of the 22nd&nbsp;Battalion who died of pneumonia in January 1917. Also in the cemetery is a monument dedicated the men of the&nbsp;1st&nbsp;Training Battalion&nbsp;(photograph right) that died and were located at the nearby Lark Hill training camp.
To learn about the Australians that are lying in Durrington Cemetery, visit the&nbsp;WW1 Australian Soldiers &amp; Nurses who rest in the United Kingdom&nbsp;project website.
Fovant
The&nbsp;Fovant military railway&nbsp;was built in 1915 from Dinton station enabling a series of camps to be built stretching from&nbsp;Compton Chamberlayne&nbsp;to&nbsp;Barford St Martin, and included the Hurdcott Camp.&nbsp;Australians were prominent at Fovant from August 1916, becoming the major occupants in March 1917. At the end of the war Fovant became a major&#8232;demobilisation centre handling thousands of British soldiers a day.</p>
<p>In 1924 a cross was erected in&nbsp;Fovant churchyard(photograph left) in memory of the forty-three Australian and twenty British soldiers buried there after dying in Fovant Military Hospital. An impressive reminder to the presence of troops in this area can be found on a nearby hill, where the&nbsp;&lsquo;Rising Sun&rsquo;&nbsp;cap badge can be seen along with seven other regiments insignia carved into the chalk, known as the&nbsp;Fovant Badges&nbsp;(photograph below).
To learn about the Australians that are lying in Fovant Curchyard, visit the&nbsp;WW1 Australian Soldiers &amp; Nurses who rest in the United Kingdom&nbsp;project website
Heytesbury
Knook Camp, Heytesbury was an Artillery training base on the edge of Salisbury plain, with Heytesbury House used as the officers&rsquo; quarters. From 1916 Australians occupied the camp. Heytesbury House was the home of Siegfried Sassoon, the first world war poet, from the 1930s until his death in 1967, aged 80.
Hurdcott</p>
<p>The camp located at&nbsp;Compton Chamberlayne&nbsp;and close to Fovant (and the Fovant badges, pictured right) became known as Hurdcott Camp as it was on land that was part of two farms, one of which bore that name. Australian battalions moved to Hurdcott in 1916, and in March 1917 Hurdcott House became the headquarters of&nbsp;No.3 Command Depot&nbsp;for the AIF. At the camp practice trenches were dug, together with a bayonet fighting assault course close to a bombing ground, and five huts were transformed into a camp hospital. In November 1917&nbsp;No.4 Command Depot&nbsp;moved from Codford to Hurdcott. By January 1919 the command depots had all but ceased to function in their primary use and were now receiving men from France on their way back home.
Lark Hill
A tented camp was first established in 1899 specifically set aside for artillery practice. In 1914, the first permanent huts were built and&nbsp;during the&nbsp;First World War, 34&nbsp;battalion&nbsp;sized hutted garrisons were built for use by all different types of military forces. By mid-1916, Australian troops were the major occupants of the camp. A light military railway line was built from the established Amesbury&ndash;Bulford line, to carry troops to Lark Hill and on to an aerodrome at Stonehenge. The wartime hutments at Lark Hill Camp extended dangerously close to the World Heritage archaeological site at&nbsp;Stonehenge, which also included ancient burial mounds or &lsquo;barrows&rsquo; in the vicinity which were vulnerable to being dug into.
After the war, the garrison became an artillery domain and in 1919 the Royal School of Artillery&nbsp;was established there.&nbsp; Today it is now one of the main garrisons on Salisbury Plain, along with Tidworth, Bulford Camp and Warminster.
Park House
Park House, situated close to Tidworth, became a depot for the AIF, housing training battalions as well as engineers and signallers, its Army Service Corps and Army Medical Corps.
Perham Down</p>
<p>Conveniently situated a mile from&nbsp;Ludgershall station,&nbsp;Perham Down was initially used at the outbreak of war by some of the new Kitchener battalions. In 1916 Australia&rsquo;s&nbsp;No.1 Command Depot&nbsp;was established at Perham Down, accommodating 4,000 men, until it moved to Sutton Veny in October 1917. The Australian Overseas Training Brigade, designed to toughen up convalescent men prior to being sent back to the front and for combat was established at Perham Down from June to October 1917, when it was transferred to Sand Hill (Longbridge Deverill).
Unlike many camps built in Wiltshire during the war, Perham Down continued with many of the wooden huts being replaced by brick buildings and is now one of the major garrisons on the Salisbury Plain. Ludgershall station, once a key transport hub for arriving and departing troops has now gone, but the railway line remains (photograph showing where the station was located, with the platform having been on the right).
Rollestone
The camp, close to Fargo and Lark Hill, was taken over in 1916 by Australian training battalions, and it was here that the reinforcements destined for the&nbsp;AIF 2nd&nbsp;Division&nbsp;and hence&nbsp;22nd&nbsp;Battalion&nbsp;were trained. With limited huts, some of the men lived in tents during&nbsp;the summer.
Sand Hill (Longbridge Deverill)
Situated close to the larger camp at Sutton Veny, Sand Hill camp was built in 1914 to accommodate infantry units. Australian troops arrived at Longbridge Deverill in October 1917, when their&nbsp;Overseas Training Brigade&nbsp;was moved from Perham Down and established there to train soldiers who had recovered from illness and wounds for a return to active service.
Sutton Veny</p>
<p>Sutton Veny&rsquo;s proximity to the Warminster-Salisbury railway line made it an ideal choice for an Army camp when the Great War started, and the camp had its own railway with a connection at Heytesbury Station. Australian&nbsp;No.1 Command Depot&nbsp;moved to&nbsp;Sutton Veny&nbsp;in October 1917 from Perham Down. Prisoners of War were also detained here and a hutted hospital opened in 1916, providing beds for 11 officers and 1,261 soldiers.
In January 1919 staff of the&nbsp;1st&nbsp;Australian General Hospital&nbsp;transferred to Sutton Veny from France, and at this time many patients were suffering from the Spanish influenza epidemic. At the end of 1919 other Australian depots in England were closing with Sutton Veny becoming the final assembling base for Australians from France, where they had mostly engaged in reburial work. Once all the troops had departed most of the huts were removed and the camp railway lifted. Given that 1st AGH had relocated to Sutton Veny, a large number of Australians are buried in the local&nbsp;churchyard&nbsp;(photograph), many of the 143 having died from the flu shortly before returning home. Included within those that died are&nbsp;61868 Pte DC Higgins&nbsp;and&nbsp;3904 Pte J Podmore&nbsp;of the 22nd&nbsp;Battalion.
To learn about the Australians that are lying in Sutton Veny, visit the&nbsp;WW1 Australian Soldiers &amp; Nurses who rest in the United Kingdom&nbsp;project website.
Every year since the end of the war the village of Sutton Veny remembers its Australian visitors, with the annual&nbsp;Anzac Day service&nbsp;at the church attended by the Australian High Commission, and the village children laying flowers at each of the soldier&rsquo;s graves.</p>
<p>Hurdcott Army Camp The camp at Hurdcott was closely linked administratively with that at Fovant. In January 1916 the 4th London Regiment found 'the Hurdcott camps were arranged on suitably designed principles with well ventilated sleeping huts and roomy messing and recreation rooms'. There were excellent training and sports grounds spread over some five acres. The 4th constructed a bayonet-fighting assault course close to a bombing ground and improved practice trenches started by its predecessors. Likewise the 4/2nd City of London Regiment, who arrived there at the same time, found it 'a really up-to-date military station'. </p>
<p>Australian battalions moved to Hurdcott in 1916. Thomas Kermode of the 8th Battalion noted in his diary that in December: 'We had practice in real trenches with dinkum bombs &amp; catapults throwing bombs, we were to have practised one of the raids you see so much about in the papers. It is really wonderful the devices &amp; wire entanglements that can be slapped up in no time. The bombs &amp; explosives used are terrifying in their intensity&hellip; A mock trench raid. Lieut Taylor who is in charge of bombing school let me dig a mine. I chose the man I wanted for a mate &amp; my old mining experience stood me in good stead. A fatigue party were trying yesterday to make a hole for putting in ammunition, but had no idea &hellip; But I knew what to do &amp; made a success of it. Loading &amp; firing it. Colonels, majors &amp; all the heads about. Bombs, rockets, machine guns, etc. Men advancing in the mud with sandbags around knees &amp; elbows. When a rocket goes up, every man lies flat &amp; still. Just like real war.' In March 1917 Hurdcott House became the headquarters of Number 3 Command Depot of the Australian Imperial Force, whose diary acclaimed the locality as ideal for a convalescent base and thought the huts well laid out and the kitchens 'splendidly equipped' and capable of feeding 4,000 men. The AIF 'taking-over party' arrived on 12 March and by the 15th 1,700 men had reported there. Initially Number 5 and 6 camps housed </p>
</div><!-- letter -->
