
<div class='letter'>
	<div class='letter_head'>

		<div class='salutation'>
			<span class='lh_el'>France</span>
			<span class='lh_el'>1st July 1917</span>
		</div>
		<p>My darling wife</p>
	</div><!-- end class='letter_header'-->
<!-- --------------------------------------------------------------------------->
<p>12 months today sweetheart is the day on which we did the deed of deeds. How time flies in one way it seems only a few months ago but when I think how long it is since I saw your dear face well it seems ages. There is one thing certain the last 8 months have been very long indeed but kiddie I don't think the time is very far off when I will see my dear  wife's face once again. This day 12 months ago was it not a great day, perhaps the greatest day of our lives unless the day of my return beats it. It may or it may not but what a day that will be after such a long separation, meeting the dear girl whose first wedding anniversary is today and our dear baby. But the wedding day what joyous recollections come to mind. Saturday morning doing odds and ends getting ready, then at last motoring down to the church with Jerry. Then a few minutes wait, a very short few minutes, eh darling. First George puts in an appearance, of course he starts the fun with his humor, then comes the girl of my heart, how beautiful she looked, then the slight trouble putting the ring on, then married, married. Could there be two happier individuals then you and I darling, of course there could not. Next the confetti, the breakfast, the train journey.  Sydney was reached, fixed up at the hotel, then a quiet stroll and then the chemist, (here the fun begins). Eventually returning to the &ldquo;Sydney&rdquo; and spent our first night. What a good time we had, eh sweetheart. Yes dearest it was great, would very much like to have been going through the whole business again today. Sincerely hope and trust that we will be together next first of July and right royally celebrating the event. Intended to send you a cable, but have not, much ready cash of course. I have money in &ldquo;Blighty&rdquo; but that's there for a rainy day. Hope you were not disappointed in not receiving a cable. Anyhow my thoughts are of you all this day and how I wish that I could have you in my arms giving you a big cuddle and showers of kisses. Sweetheart take these XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>

<p>Suppose you would like to know what I'm doing today well at 2 AM I went on a horse picquet<span class='fn'>french word describing a small military post closer to the enemy than the main formation. Often used in the phrase 'picket line'.</span> and remained there till 11 o'clock then I went out on patrol. While at my post an old woman came and spoke to me. She was a refugee for Anas. The afternoon was cold so she brought me a glass of hot coffee which I greatly appreciated. Returning from patrol at 6 PM have had tea and now about to go and see one of my boy friends. Will finish this letter tomorrow and state how 1st July finished. Having a green envelope I intend to make the most of it. Good night darling take these anniversary kisses . XXXXXXXXXXXXXXXXXXXXXXXXXXXXX Love Don</p>

<p>Before letting you know how I finished up last night I will try and give you a little news. Last Friday I received 16 letters was not that great; 4 from you darling, 1 from mum, 1 Auntie Alice, 1 Auntie Edie, 1 Stan Fry, 1 Mrs. Mannel, 1 Miss Sutton, 2 Nellie Fry, 1 Mrs. Smith, 1 Harry Beardsmore and 2 from Phyllis. Was that not grand, for one mail, tell you kiddie I was worse than a youngster with a new toy. Will answer your loving letters altogether in this one. I understand there has been a lot of mail from here to Australia gone to the bottom, sincerely hope, kiddie you receive all mine, especially the album of 96 photos also the souveniers of Salisbury. I also sent an album of photos containing 12 views to dad, mum, Auntie Em and Phyllis and your mother. They were posted on different dates so some of them surely will arrive okay. Phyll in her letters tells me that you and she have some good chats on the phone. Wish I could ring you up from here darling, what a long talk we would have to be sure. If I can't talk to you by phone, you know, dear that my thoughts are continually of you, and hoping and busting that we two are able to embrace one another very shortly and continue the joy of our married life.</p>

<p>The daylight savings business seems to be causing a great deal of trouble, why I cannot say, it is in vogue in England and France and every soldier to a man thinks it just the thing. In our opinion it is most suitable for Australia than for this country. But never mind it can be all day or all night so long as I get back to my darling wife and little one.</p>

<p>No cable yet I am on pins and needles. Have not had any letters from Keith lately but by the last letter he was well.  By jove he did have a good time at Cape Town, did not want to leave and from what he told me there was a girl in the case, in fact girls. Jerry is getting gay<span class='fn'>Gay  - in this period the term was originally used to mean "carefree", "happy", 
"likes a party", or "bright and showy".</span> somewhat. Harry Beardsmore is down at the base in  Le Harve. He said he if ever I should be going through to be sure and call on him and if at any time there is anything he could do for me to let him know straight away. If I could only get to the base for a while then would be something doing to be sure. Saturday afternoon we received a few Christmas comforts, rather late don't you think, but better late than never. They were gifts donated by Melbourne people. I got a tin of cocoa and a tin of paste. I may state the men see very very little of the comforts sent from Australia and when they do it is only what other people don't want. They pass through too many hands before the right people get them, the right people are privates and gunners. Last Friday I had the day off so left camp at 8 am for the city of Amiens. Had to walk about 4 miles to the main road, and then caught a motor bus. It was a glorious run into the city, the road running through an avenue of trees for 8 miles. It was a sight for sore eyes. On the way we passed hundreds of German prisoners working on the roads, also numerous motor lorries carrying French soldiers to the line. Had a good look around the city, the best part of the day was when I was feeding. I just had enough money to get myself a few good feeds.</p>

<p>Pay day again today so I am right again for a few weeks. When we are in camp there is very little  to buy so I don't require much money. It's when you take these trips to Amiens that the money goes. I got home that night about 9 o'clock and waiting for me was the batch of 16 letters so that was a glorious ending to a good day. </p>

<p>Had just gone to bed on Thursday night when  I was told that I was wanted downstairs. Of course I got up and looked out of the window and who should it be but Stan Coldrake. He is camped in the same village as myself. Stan had been visiting the 2nd DAC that afternoon and heard to his surprise that I was in the 15th Battery. So he went to the 15th looking for me only to find we had shifted. He was very disappointed and then asked where we had gone and to his surprise was told the village in which he has been camped for about two months. Fancy the two of us being in the same village for over a week and not seeing one another. Anyhow he came straight to our billets and got me out of bed. What a good talk we did have to be sure. Saturday night we had a few hours together, Sunday midday we had a few minutes together, I intended having dinner and tea with Stan but duty presented me from doing so.</p>

<p>Darling I finished off the day of the 1st July by spending a few hours with Stan up in his hut. Will see him tonight if possible for we are leaving here tomorrow returning to our old camp, for how long I cannot say. Stan is a cook at present only a temporary job he's on a good wicket and hopes it will be permanent. He is cook to about 20 sergeants in a school. Nellie Fry told me about Bernie Curtis being seriously wounded and that he was doing well, Best of luck to him. She had a great job in finding anything out about him but eventually after a great deal of trouble she was rewarded. Nellie mentions having sent you a cable about Frank, also stating that I was in France and well so I am. In  a letter to her George said he expected to be going over to England in about three weeks time for 10 days, if that is so which I sincerely trust is right, he should be over there now, having a good time, lucky beggar. Nellie tells me Sid Fry is having a good time with the nurse that nursed him during his illness. In fact he's making the pace. Also  she tells me George has received your letters dated 15th and 23rd April while in hospital. The letters I received from you kiddie were numbers 22, 31, 36, 37. Number 22 was dated January 24th so therefore it took a long time in finding me. Of course the address was the cause of the delay so in the future address my letters care of Nellie Fry or to the 15th Battery A.F.A.;  A.I.F. France. In addressing them to Nellie leave a space at the bottom of the envelope for the re-address.</p>

<p>You want to know what the meals are like well all I can say is that three together would not make a decent 11 o&rsquo;clock. We are as good as the &lsquo;Dagoes&rsquo; able to live on the smell of an oily rag. So you are still busy with the little pretty things, what what I give to see you working at them. Auntie Alice in her letter told me you had a glorious collection and how I ought to see them, so I will shortly, I hope, eh kiddie. Can easily imagine what your trip through the Newcastle shops would be like, suppose you had a look at baby clothes in every shop why should you not being the wife of Donald C McDonald. Yes Kiddie I'm looking forward to our stay at the &lsquo;Sydney&rsquo; of course we will have to have a bed not a cot for a cot may be too small for the twins, don't go crook now dear.</p>

<p>Got rather a shock regarding the money business but in one way I'm not surprised they are taking into account the deferred pay but that does not matter. They agreed to give me 
&pound;2, less any deductions. Of course the deferred pay should be deducted as long as they don't cut it down anymore. Of course it must be taken and nothing said for I am extremely lucky to get any money at all. Everything is okay in that way. How is the military treating you, suppose everything is alright in that direction.</p>

<p>Wish the fig and ginger jam also the cake would hurry up and come, by jove sweetheart, it will be more than special as it was made by you kiddie. The trouble is when you get these nice things they go too quickly. I'll bet the fig and ginger won't last long. I'm very pleased indeed kiddie that you sent the photos of the <?php render_mother("Mata");?>, certainly they are not very good but when I look at them they send my mind wandering back to that time I took her photos in the garden. What an old fidget she is when the camera puts in an appearance. As soon as I get back she will have to put up with having her photo taken a good number of times so she had better start and get ready.</p>

<h4>3rd July</h4>
<p>Making another start kiddie. In your letter number 36 you mentioned about my receiving your photos, of course you have heard, long before now, that I got them okay. So you have had Rose over again, coming in quite unexpectedly. Very sorry to hear that collie dog of Muriels has died, it was such a fine dog too. Miss Sutton in her letter gave me all the office news, also mentioned that she had received the photo. I forgot all about that photo.</p>

<p>Yesterday I was out patrolling again returning about 6 o'clock. Soon as I got back I got a great surprise as two of your loving letters and one from Mrs. Smith were waiting. After I had read them I went up to spend the night with Stan, also to have tea with him. He is a bosker cook, there for my &lsquo;little many&rsquo; got well filled. This is what I had; roast beef, roast potatoes, onions and sauce, rice and custard and 2 cups of tea. Tell you kiddie it was just great. After tea he and I went over to a farm and helped a French woman do her milking and when  we finished we carried it home for her. Needless to say I made the milk smile. This Frenchwoman is the happy mother of a baby boy about a month old, a lovely kid, name is George. Her husband is up in the line at present and she is running their farm expecting the war to end in three months time. I returned fairly early to our billets as we moved off again today. We left at 9 o'clock for our old camp arriving at 3 o'clock. I did the journey by bike but was very unlucky I had four punctures. Have no idea how long we are staying here but do not think it will be long before we are on the move again. The two letters I received last night were numbers 38 and 42. By jove kiddie, you have no idea how pleased I was, absolutely overjoyed to hear you have received a large batch of my letters, well that was simply great, glorious news.</p>

<p>So you think it is time I started to be good, why sweetheart I have always been good. We don't get many opportunities here to go to church. I'm getting to be a heavy pipe smoker kiddie, it is good company in these parts. Yes darling if there are any decent jobs about I will try and get hold of one for your sake, sweetheart and little Macs. I am at present on the battery staff of the 15th battery. Can easily imagine you, kiddie, the <?php render_mother("Matar");?> and the <?php render_father("boss");?> comparing letters must have had a good time. Yes kiddie always number your letters it lets me know exactly how there are coming along. Sorry I did not keep up the numbering of mine. You seem very pleased about the change to the old time. I will tell you this time next year what I think of it, that will be the time, eh love. Yes dear I know well how you move about in bed at night. I&rsquo;d give thousands to be in bed with you tonight darling but the time will come again, then what oh, eh what, don't mention it. Very sorry to hear that your father has not been too well also that Donnie has had trouble with his teeth. Have to laugh about Mrs. Hill and the ring, hope she does not succeed. The photos of we two and  Charlie are simply great, I was extremely pleased to get them. Good news came through today it is to the effect that the Russians have started by capturing 8000  prisoners on the first day, sincerely hope they keep it up, for it is sure to make a big difference as to when peace will be declared.</p>

<p>The United States Army is over here now, they  have been here over a fortnight. It's not a small force by any means either. The Germans will now start to scratch their heads.</p>

<p>Darling is it a boy or a girl or boys and girls? I am anxiously waiting for the cable, it should be on its way by this. Sincerely hope and trust that everything went off okay and that my dear wife did not have to put up with any unnecessary pain and that you darling and our baby are both doing well. Have been trying to think how I will feel when the joyous news comes along, suppose I will go nearly mad with delight. Can assure you dearest that I am greatly excited at present waiting for the news. What's the baby to be called? Suppose names will be well pulled about before a final selection is made. Wish I could be with you all to have a say but i am sure that the selection which you make kiddie, will suit me, and so we two are the chief people to be pleased, everything in my opinion will be just it.</p>
<div class='closing'>
<p>Well darling it is getting dark, we have no lights so will have to close. Anxiously waiting for the news. I'm grand kiddie, Best of health. Love and kisses to my darling wife from your ever own and a loving husband with tons and tons of kisses and embraces galore.</p>
<p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Your loving husband</p>
<p>Don</p>

<!--p>*&nbsp;Picquet&nbsp;(military), a small temporary military post closer to the enemy than the main formation</p>
<p>** Gay  -The term was originally used to mean "carefree", "happy", or "bright and showy". </p-->
</div>
</div><!-- letter -->
