
<div class='letter'>
	<div class='letter_head'>

		<div class='salutation'>
			<span class='lh_el'>Sand Hill</span>
			<span class='lh_el'>26th February 1918</span>
		</div>
		<p>My Darling Wife and Bonny Son</p>
	</div><!-- end class='letter_header'-->
<!-- --------------------------------------------------------------------------->
<p>Just after posting your letter on Sunday I received a great and joyful surprise, the postman walked in and handed me 12 letters, just lovely. Talk about excited no name for a kiddie. 8 were from you darling, 1 mum,1 Phyll, 1 Daph, and 1 from &ldquo;Ma&rdquo; Fry. On Monday I had another day of days, two parcels came to hand, one from Mater and a cake from my darling son. The Maters parcel contained just the things I needed, hence very very welcome. The cake was bonza, in excellent condition, the wording&rdquo; With love to dad from little Don&rdquo; was not broken at all except for the &ldquo;D&rdquo; in  Don. It's all gone so that speaks for itself. </p>
<p>It is marvellous how fresh cakes keep considering the trip of 14,000 miles. Had a letter from Keith today, he is grand. Was speaking to George today, expects to be going on leave tomorrow for two days. Ran across Jack Ken today, he is returning to France later in the week. Saw a photo of Mrs Hewitt and her baby girl this afternoon, very good indeed, she looks very well to say nothing of the baby a fine little girl. The numbers of your letters sweetheart our 121, 122, 123, 124, 125, 126, 127, and 128, that's a good straight run what say you darling? You appear to be having a good time at the lake, why can't I get back and join you in having a good time. Now mind darling when I return we will make up for it, make the pace some eh kiddie. Won&rsquo;t Bubs have a good time, oh don't mention it. Its glorious to read in your letters that both you and darling Neville are keeping best of health. Can assure you it is a great relief to know my two darlings are better than okay. Something will be doing at the Sydney, bet your sweet life. Your question kiddie &ldquo;Who are you going to kiss first Me or Bubsie&rdquo; requires answering. Well dear, don&rsquo;t think I will answer it, wait till I return then we will see. The best way out of it will be for you both to kiss me at the same time. But I'll make such a bull dog rush at you both, that we will be all sixes and sevens. Anyhow take one each now X X. By jove I wish I could see Bubsie in the water, I'm dying to get back to see him, but of course I'll have to wait and be contented, although it's very hard to be contented with this military life. Soldiering is not in my line, I want to be with my two dears, that and our own &ldquo;home sweet home&rdquo; is the life for me.</p>
<p>No, kiddie you did not tell me, you enclosed a pair of socks from Mrs Price. Will certainly drop her a line one of these days. So Elsie is engaged, good luck to her, tell her from me to get spliced straight away, don't delay, there's nothing like it, married life I mean. </p>
<p>You appear very disappointed with the conscription issue and rightly so. Cannot make out what the country is coming to. Reinforcements are needed and badly needed. The result is a disgrace to the Australian empire. Certainly there are a number of reasons against conscription but the reasons are tenfold more. Conscription it should be. </p>
<p>Yes kiddie your Christmas cards are some class, very nice indeed, the wording good, some class my wife. Pleased to hear you receive my photo. The snaps that Nellie sent you are awful. I'm better looking than they indicate, you know that well dear.</p>
<p>The photos you sent are simply great, showed them to George today, he thought Bubs just it. Bubs in the act of yawning is grand, wish I could stick a lump of lolly in his mouth. All the photos of Bubs are jolly fine, especially the ones having a bath. He&rsquo;s got a bonny grin. He's a bonny kid. The group photo is good, except you kiddie, look like if you&rsquo;d taken are willie. Will send them on to Nellie in a day or so, but if she does not return them well, Nellie had better look out. She won't keep them, she's not game. The Mater in her letter said she and Phyllis were, going down to Toronto for a few days, very pleased to hear this, for I'm sure she needed a wash. If mum got into the water it would be good night Toronto.</p>
<p>Dear ones supper is just about ready so will now say good night and happy dreams. Oceans of love and kisses galore to my darling son and darling wife XXXXXXXXXXXXXXXXXX from your ever own loving husband and Dada we've are a few extra specials
XXXXXXX loving husband and father XXXXXXXXXXXXX</p>
<p>Don</p>
</div><!-- letter -->
