
<div class='letter'>

		<div class='salutation'>
			<span class='lh_el'>Sandhill Camp</span>
			<span class='lh_el'>25th January 1918</span>
		</div>
<p>My darling wife and funny son</p>
<p>Well kiddie it's over a week since I've written, very sorry, but I'm sure you'll forgive me when I tell you all. Last Sunday week I received a wire from  Keith stating that he was in Blighty on 14 days leave and that he was coming out to the camp on the Monday. He put in an appearance about 5 o'clock in the afternoon. Cannot tell you how pleased I was to see him, he is looking grand, never saw him looking better. After a good talk we went for a walk up to see George. You ought to have seen the look on George's face when Jerry went up to him. They had so much to say that they did not know where to start. After another talk we returned to our hut had supper, then turned into bed together. It was the early hours in the morning before we got to sleep. Jerry has been having the time of his life in France, does not wish to come back to England, says France will do him. Early next morning he left for London where he expected to have a good time. Darling I've just returned from a weeks trip to Edinburgh. Had the time of my life. Keith was coming up with me, had to meet me last Thursday night at the station, intending to go up together, but very sorry to say he failed to put in an appearance. Anyhow I went on without him, expecting him up next day, but up to the present I've not heard another word from him. He must be having a good time somewhere, suppose he's got a girl somewhere. Kiddie it is a great place, the Scotch people grand. I stopped at the Crown Hotel as soon as the people knew my name they could not do enough for me. Visited all places of interest, Edinburgh Castle, Holyrood Palace, Giles Cathedral, and up to the top of the Scots monument etc etc. Have a number of postcards which of course dear I'll send along. On Sunday I went for a trip up the Firth of Forth. The bridge is wonderful. While there saw the &ldquo;Australia and New Zealand&rdquo;. They had just come in from the North Sea for a 14 day overhaul. Went to all the theatres to be sure. Always had a &lsquo;box&rsquo; did things in grand style. I knocked about with two Scotch commercial travellers, who had nothing to do, so took me around. Scotland will do me kiddie. Wait darling till I take it you and Bonny Bubs for a trip to Scotland. Returned to London yesterday morning, had the day there, went to the theatre in the afternoon and witnessed &ldquo;The Maid of the Mountains&rdquo; simply glorious. Returned to camp this morning, so dear I'm dead tired. Made several attempts while on leave to write but as  sure as I&rsquo;d start my mates would get hold of me and take me out. They would not let me pay for a thing. If I attempted to pay they would go crook, gave me a royal time, and fine chaps they were. Both had fought in France and had got their discharge.</p>
<div class='closing'>
<p>Darling I bought Bubs a mug made out of the real Scottish horn and Silver mounted will post it  in a day or so. Sweetheart I&rsquo;d have  given all I possess, could I have had my two darlings with me, what a grand time we would have had. Never mind wait until I return then things will be doing, eh kiddie. Enclosing a couple of postcards. While away on leave, a number lost their jobs, but yours truly, is still going strong. Great alterations are taking place in camp. Everybody is wondering who will be next. Will write again in a day or so giving more particulars of my trip. </p>
<p>How is darling Bubs getting on and how is wifey dear. Sincerely hope both are just okay. Love kisses and embraces to my two darlings from your ever own loving hubby and father with scores and scores of kisses and embraces.   </p>
<p>XXXXXXXXXXXXXXXXXXXX, Don</p>
</div>
</div><!-- letter -->
