<div class="letter">
<h2>Sunday 10 December 1916</h2>
<p>My darling wife</p>

<p>It took two and a half days from Durban to Cape Town. The run along the coast was very tame really, nothing of importance to relate. We arrived at Cape Town last Monday morning at 1:30AM  and anchored in Table Bay until light in the morning. Happened to wake just as we entered the bay to see what there was to be seen of the town.</p>

<p>The lighthouse and lights of the city shone out and looked very pretty but nothing to be compared with Durban. After breakfast into the harbor but not a visage of the city could be seen owing to the fog. As the morning drew on the fog gradually lifted, by jove dear it was a great site first could be seen the wharves, then portions of the lower parts of the city, then the very large buildings, denoting the business district, later the low hills the locality of the best residences then last but not least the mountains put in an appearance.</p>

<p>Table Mountain looked glorious and for the best part of the day clouds hung onto the peaks, it was a sight which will take a long time to forget. My own desire was to have you with me to share the grandeur of the scene. Our steamer birthed at the same wharf but opposite a large Dutch Mail steamer the Princess Juliane. It was great to see the passengers coming off, all the latest fashions. The passengers threw us cigarettes, and cigars galore. I got a number of cigarettes, but just missed a large box full of cigars. Of course I got some of them. Several boxes much to the disappointment  of the boys fell in the water, the seamen rescued these and shared them with the boys but of course they were wet. Shortly after, the health authorities came on board and inspected this ship with the results we were placed in quarantine. There was a little sickness but no need for the drastic measures taken.</p>

<p>The boys went nearly mad, they have not got over it yet. A march was arranged. We first marched to the sports ground and on the way Kiddie this will make your mouth water, there were scores of Niggers selling strawberries, oranges and pineapples and the quality I have not seen anything like in Australia. The strawberries were absolutely great, large as peaches, Rich red color and cost 3c per basket of 20 to 30. I tell you darling I had a number of baskets. I made a pig of myself don't you think. When we arrived at the sports ground dinner was waiting for us and of course we did it justice. Afterwards a sports program was going on between the troops. The artillery taking off the majority of the prizes. The prizes were donated by the cape town people. Strict orders, (under penalty of cells all the way to London), were issued prior to going off the boats. This is what the order was: on arriving at the grounds no man was to either leave or enter the grounds on any excuse as no leave of any description was to be allowed men  or officers while off the boat. Well the boys thought that too rough with the result that hundreds jumped the fence. That caused a great stir, I'm among the officers and a parade was at once called. We were then told all sorts of things would happen if we broke leave, the only penalty not mentioned was dead at sunrise. Anyhow things were quiet for a time. After the sports we were marched through the streets and eventually arrived at the “Feather Markets” where tea was ready for us. The market is a very large building where ostrich feathers  are sold by auction, did not see any feathers, on the outside were large posters of welcome. On entering the building a fine sight met our eyes, table set for 1600 men loaded with  eatables, hundreds of flags hanging and the stage decorated with flags and palms on which was a band playing a tune of welcome. Each man took up his position at the table and a short address of welcome and good wishes was delivered by the chairman. After that a photo of the hall from the stage was taken, it took several photos to take in all the boys.</p>
<p>Then we set to and had our fill which we thoroughly enjoyed. While making short work of the good things provided the band played popular tunes to which the boys, everyone of them, joined in, and talk about a noise, fancy 1600 men singing at the top of their voices. Under each plate was a postcard to be used straightaway to be sent to our friends at home. I posted mine  to you my darling there and then. A receiving box in charge of a lady was there for our convenience. After having our fill we went outside and lined up again giving the people a great cheer of thanks. Before leaving I had a talk with the chairman regarding the photo taken, of course trying to get you one my dear. He made arrangements to have the photo taken so as to give each one of the lady helpers for Christmas. I told him my reason for wanting one so sweetheart he is going to send you one, the photo on which I will be. He told me to tell you he would send one and to let him know you received it okay. Gave him your address. </p>

<p>This is his name and address</p>
<pre>Mr. A W Townshend chairman
Visiting troops entertainment committee
Cape Town</pre>

<p>The whole of the days entertainment, was carried out by the Australian and English ladies, not by the Cape Town ladies they have no time for Australians. After leaving the hall we made our way back to the boat. On the way we past scores of black women, talk about morals, their carrying on could not be placed on paper. I've often heard of them carrying on but these women beat the band. We should have left port 7 o’clock, but when the time came for sailing there  were about 200 deserters, they got all but 28, and they are still missing. Eventually got away about 11 o’clock. The stay at Cape Town was very good, but what we wanted was leave, it did not matter what they did for us, the boys was very disappointed and will forever have a bad word for the officers who were absolutely too blame.</p>
<p>Will enclose a rough plan of the hall where you will find me in the photo, also I am well in the front. Out trip since leaving has been very tame, beautiful weather and calm sea. We are in the tropics at present but it's unusually cool, suppose we'll strike hot weather in a day or so. Enter the danger zone next week, then for an anxious time. On the 5th passed a large passenger steamer bound for Cape Town. Darling the sea water soap is a great boom, wish I had more of it. On Wednesday had a tooth out. One dentist would not have a go at it, frightened it would snap so gave the job to another. He did not like the job either. Anyhow it came out whole and no pain. The dentist was congratulated by all the other medical men and the dentist told me it scared him and to think myself the luckiest men on the boat. Anyhow I'm alright now. Regarding my vaccination had a sore arm but not too bad, did not swell only got tops on the parts scratched. It's okay now.</p>
<p>Last night there was a grand concert, absolutely the best it's the last now until we reach the old Blighty
		<span class="fn">Blighty, or Old Blighty, means England</span>.</p>
<p>Went to communion this morning at 6:30 also to church at 10am may go again tonight. Suppose darling you say I'm getting good but not before time.</p> 
<p>This week has been devoted as far as sport is concerned to boxing and tug of war. 
Sweetheart at Cape Town I sent you a packet of postcards 12 in all they are of Durban. Let me know if you receive them. In two other envelopes I sent you several copies of  “Benalla Jim”. They are very poor papers but will give you some idea of active service papers. Have a look at number seven there is something there which I am sure will interest my dear wife. I've marked it kiddie. Owing to health reasons sweetheart I've taken on smoking a pipe and cigars. Very heavy smoking too, dear will explain reasons later, when I arrive in the old Blighty. This won't be posted until we arrived in the Blighty so suppose you'll get both letters together. Enclosing a photo of your old hubby but it is very poor, also enclosing two silver leaves. There are only three trees of this class in the world and they are on Table Mountain. The trees bare three times a year hence the leaves are fairly plentiful in Cape Town.</p>

<p>Well dear old girl I'll now ring off for a few days hoping you are in the best of health. How are things progressing with you dear wife.</p>
<p>Love and kisses to my darling wife from your ever true and loving hubby.</p>
<p>	Don</p>
<p>Also enclosing another photo. Do you think I'm getting fatter, they all say I am? </p>
<p>Love to my darling.</p>

</div>