<div class="letter">
<h2>Thursday, December 20th 1916</h2>

<p>My darling wife</p>

<p>I arrive at Freetown the capital of Sierra Leone last Friday morning and left at 6 o'clock o'clock this morning. Sierra Leone is a portion of the Gold Coast and  is known as the white man's grave.*
<span class="fn">It was for Sierra Leone, which in 1807 had become Britain’s first West African colony, that the term ” White Man’s Grave“ was originally coined.  It had been conceived as a home for slaves freed after slavery was declared illegal in Britain In 1772.  A humanitarian doctor suggested Sierra Leone would be ” a permanent and comfortable establishment in a most pleasant and fertile climate“.  It was a virtual paradise, he explained, ”where a man possessed of a change of clothing, a wood-axe, a hoe and a pocket knife could soon make himself at home“.
<br/>But reality was very different.  The first batch of slaves had mostly been flamboyantly dressed flunkies in stately homes and town mansions.  Easy prey to tropical diseases, without any proper system of government-sponsored hygiene, they died in scores.  Missionaries who followed them out there found things equally tough.  They were only being realistic when they spoke of “seeking martyrdom” there.  One society lost 53 of the first 79 it sent out.  “I looked upon the land” wrote James Norman of his arrival in Freetown in 1821, “as my burying place”.
<br/>Government servants fared no better.  During one seven-month period Sierra Leone went through 4 acting governors; two died in office and another, mindful of his predecessors fates, left the colony when he fell ill.  On another occasion, a governor returning from a trip found his administration had no lawyer, no chief justice, no secretary, no chaplain, and only one schoolmaster.
</span>
</p>

<p>Where we anchored was in a bay with the town to the right. It's very pretty and interesting entering. The first thing to catch ones eyes was the hills, green as can be, covered with palms and tropical vegetation, next came a recent wreck we thought we thought it was a steamer standing off the shore, but it was sitting firmly on the reef, a very fine steamer indeed. Then we passed a number of beaches that were very pretty indeed, before these  beaches we passed the lighthouse and one of the forts. On a very high hill could be seen the main fort and wireless station. Shortly the town came into sight situated at the foot of the hills but very scattered. We were met by a number of canoes paddled by niggers, when we anchored, which was on the stream off the town, they started to sell fruit and fish. Their way of fishing is to tie the line around their neck or toe and paddle about. It's very funny indeed to see them when they get a bite. </p>

<p>Freetown has a population all of 250,000 all blacks and there about 20 whites. The streets are about 15 feet wide and very dirty. The buildings are from one story to five or six but they are all liable to fall down at any moment. Every second building is a church and  they are very fine structures. The people for a living barter in fruit and cattle, the cattle being of a very small class. 1/0 per day is conceded a very good wage. There is no such thing as trams, cabs or rickshaws have to walk everywhere about the scattered town. There is a train which runs to a place called Whitetown about 13 miles away fare 6 each way. The name indicates the class of people living there but half the population are blacks. These black people are great churchgoers, they are mostly Methodist, Church of England, and Roman Catholic. On Sundays every person from the youngest to the oldest goes to church, they consider it practically a crime not to go and then on the weekdays they carry on to beat the band. Nearly every man and  woman more or less goes about naked. The washing of the clothes, what there is of them is done in a fast running creek, the clothes being hit with stones and sticks. I did not have the opportunity to see the town as well as most of the boys who were going ashore yesterday for the day, but we received sailing orders so had to remain on board. There were nine transports in the bay Marathon, City of Spasa, Afric, Argylhill, Boonah (once German owned) Benalla, 
Port NIcholson, Sumartrer, and Bordeau, two cruisers, Kent and Highflyer 1Aux Cruiser Orataba, one passenger boat, Saxon, and four other boats.</p> 

<p>The heat was terrific being always over 100°. Strange to say it was winter, summer is only 4° hotter but it  is  continually raining, then fever runs throughout the whole country. Left Sierra Leone at 6 o'clock this morning. Headed by Aux Cruiser the following five transports in order made for sea Boonah, Benalla, Port Nicholson Argylline and Afric. At present the five transports are in one long line about four ship lengths between one another and the Aux Cruiser has taken up her position to port. Expect to arrive at Dakar in a day or so and pick up our guns. Not one of the five have guns. No doubt you heard of the German raider and submarine that were in the North Atlantic. We understand that they have been accounted for. There were 11 British boats out for them. The Border, one of the transports after getting out of Sierra Leone 100 miles had to turn back. Naval men off the King Alfred told me that on a new class of British boat  they carried 17 inch guns, also that a number of boats carried 16 inch guns.</p>

<p>The weather today is beautiful not nearly as hot as when in port, we were glad to get away. The sea is as smooth as glass. Plenty of sickness about, hospital overcrowded, mumps everywhere you look , these patients are not taken into hospital but allowed to sleep, eat and mix generally with all the men. It's a case of who will be next.</p>

<p>About half an hour ago there was a burial of a young man named Bailey of the 1st Battalion. The cause is not definitely known but it was not meningitis which the other five died from. In my last letter I gave you full particulars regarding these deaths I think, in fact I’m sure.</p>

<p>Monday is Christmas day my darling and I have not sent you a present but I'll do so as soon as I get to the old dart. The  trouble was I intended to get you something at Durban the second day of our stay but we left early. Cape Town had no leave, then same at Sierra Leone never mind darling I have not given up hope I will try and get something at Dakar if not at the old dart.</p>

<p>Well sweetheart this is all there is to tell about  our last port. Will write again after leaving Dakar. Hope you are in the best of health. How are you progressing dear wife?</p>
<p>Remember me to all. Feeling fit.</p>
<p>True and sincere love to my darling wife from your loving husband with lots of love and kisses.</p>
<p>Don</p>

<p>Can guess your thoughts when you first heard of the peace proposal. Suppose you know what mine were anything to get back to you love, anyhow it may not be very long.</p>
					<p>Love to my darling</p> 
						<p>Don</p>

<p><bold>PS</bold> Last night a sailing boat tried to enter the bay after dark. It was met with a shell from one of the Forts, no damage done, caused great excitement. I was in a position which gave me a full view of the whole proceedings. No beg pardons where the Navy is concerned. Naval  men man the Forts.</p>
</div>

<div class="fnote">
*
<p>It was for Sierra Leone, which in 1807 had become Britain’s first West African colony, that the term ” White Man’s Grave“ was originally coined.  It had been conceived as a home for slaves freed after slavery was declared illegal in Britain In 1772.  A humanitarian doctor suggested Sierra Leone would be ” a permanent and comfortable establishment in a most pleasant and fertile climate“.  It was a virtual paradise, he explained, ”where a man possessed of a change of clothing, a wood-axe, a hoe and a pocket knife could soon make himself at home“.</p>
<p>But reality was very different.  The first batch of slaves had mostly been flamboyantly dressed flunkies in stately homes and town mansions.  Easy prey to tropical diseases, without any proper system of government-sponsored hygiene, they died in scores.  Missionaries who followed them out there found things equally tough.  They were only being realistic when they spoke of “seeking martyrdom” there.  One society lost 53 of the first 79 it sent out.  “I looked upon the land” wrote James Norman of his arrival in Freetown in 1821, “as my burying place”.</p>
<p>Government servants fared no better.  During one seven-month period Sierra Leone went through 4 acting governors; two died in office and another, mindful of his predecessors fates, left the colony when he fell ill.  On another occasion, a governor returning from a trip found his administration had no lawyer, no chief justice, no secretary, no chaplain, and only one schoolmaster.</p>
</div>