<div class='letter'>
<h2>Camp 26, 13th April 1917</h2>

<p>My darling wife</p>

<p>Every day this week there has been a delivery of Australian mail to the boys but yours truly received none, until tonight when darling I was overjoyed in receiving 9 letters 4 from my little wife, one your father, one  Don’s and the remainder from home, simply great. The numbers of your letters darling were 24, 25, 28, and 30. Will answer number 24 tonight the others in a day or so.</p>

<p>Yesterday 12 April was officially the first day of summer. It snowed all morning and rained in the afternoon a good opening for summer, I don't think. Give me hot weather before cold. Australian weather will do me, no matter how hot. Last night after tea I went for a stroll and on the way back to camp make Ray Prior and Herbert Mannall. Ray is looking well. We got speaking about doings of Maitland, of course he told me he got married before leaving, how he wished it to be a small  and quiet affair, and it turned out a big “do”. He has grown a mustache which in my opinion does not improve him although I did not tell him that.</p>

<p>Darling you have not mentioned having received my Cape Town letters. You may have done so in the letters that are still missing. I left to be posted a very large batch of letters. You say you wonder what I do on weekends, well several of us go on walking trips to the different villages. But I would sooner be back with you darling and the children ( as you say) it would be glorious but sweetheart the day for my return is getting closer then we will have the time of our lives eh kiddie. Won't it be grand to see mum and dad and the children out for a walk on Sunday  afternoons. Don't mention it. Guess the Matar would be excited but I would like to know what the boss has to say, wait until he is called “Grandfather”. There’s no tommy twaddle at all dearest, I like to hear everything in detail, why shouldn't I, so keep going kiddie give everything (about the greatest child that was ever born) to me in absolute detail. Not too much about the “camping coat”. I am extremely pleased to hear that you are keeping in the best of health, it’s simply grand to hear that my dear wife never felt better in her life.</p>

<p>Mrs. Crowley is boarding at Durrington about one and a half miles from here, her hubby goes and has tea with her every night. Lucky beggar. Have not received your photos yet dear, sincerely how it hurries up, will be anxiously waiting for every mail to get my dear wife's photo. Like yourself we have no idea when the mail goes, so just post the letters and chance the mail. Have not received the parcel yet. I received a letter from Keith today making arrangements for our meeting tomorrow. But I am afraid I will be doing a little duty tomorrow, with good luck I will get out of it. He mentioned having received your letter also that he had a great time while on leave. Next Tuesday is the day set aside for the inspection by the king. We don't care a hang about the review, what we care about is the four day leave which we hope to get. If we get the leave, the money, darling, which you sent along will certainly come in handy, will ensure me a jolly good time.</p>

<p>It's bitterly cold and no fire so kiddie, I think I will turn in. Very pleased indeed to hear you are keeping in good health and everything is progressing okay, towards the day of the great event. Keep in good health darling and then nobody need worry and everything will be just the thing. Au revoir to my sweetheart and wife we tons and tons of kisses from your ever own and loving husband with kisses and embraces.</p>

<p>XXXXXXXXXXXXXXXXX       Don</p>

</div>
